var mapLevel = [
    "                      ",
    "         o      X     ",
    "X       Xo    3      o",
    "   XXXX      oXX o   X",
    "  X   o      o   o    ",
    " o    X 3    o   o    ",
    " o      o X  o H o    ",
    "XX     XHXXo   H o    ",
    "   X    H  o   HXX  H ",
    "    X   H  o      o H ",
    "    1Ho H  o      X   ",
    "X o oHo X oo  o  o 3  ",
    "  3  Ho   XXo o  XXXXX",
    "  X oHo     XXH       ",
    "X       Xo           o",
    "   XXXX    H oXX o  1 ",
    " 3X   o    H o   oH   ",
    " o    X o  H o   oH   ",
    " o  3 1o     o   XXXXX",
    " o  X   o X  o H o    ",
    "XX     XHXXo   H o    ",
    "   X    H  o   HXX  H ",
    "    X   H  3      o H ",
    "     Ho H  o      X   ",
    "X o oHo X oo  o  o o3 ",
    "  o  Ho   XXo o  XXXXX",
    "  X oHo     XXH       ",
    "X       Xo   3       o",
    "   XXXX  H   oXX o   X",
    "  X   o  H   o   H    ",
    " o    X H    o   o    ",
    " o      o X  o H o    ",
    "XX     XHXXo   H o    ",
    "   X    H  o   HXX  H ",
    "    X   H  o      o H ",
    "     Ho H  o      X   ",
    "X o oHo X oo  o  o o  ",
    "  o  Ho   XXo o  XXXXX",
    "  X oHo     XXH       ",
    "     Xo   o   Ho   o  ",
    "   oo o   X   Ho   o  ",
    "    X o  3 X XXo   o  ",
    "      o        X   XH ",
    "   o 3o        o   oH ",
    "   XXXX o      o    H ",
    "  X    XX    3 XX  oH ",
    "oo           X   X  H ",
    "oo  o    3 OX   o  XX ",
    "XX     o   X    oo    ",
    "    o3 o         XX   ",
    "   XX  o     3  oo oo ",
    "      oH  H  XXXXXXo  ",
    "       HX H  3     oo ",
    "  1 o3oH  XXXXX    o  ",
    "   oXX H       XXXo  o",
    "   X  oH             X",
    "    o  H       X   1 ",
    "    X oH3   X     oXX ",
    "    oH HXXo3    o X   ",
    "    oHXX  X ooo XX   3",
    "     H      XXX    X  ",
    "   XoH ooo            ",
    "     H                "

];

